// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVa0c9YtcwOOjCDnY1-XAiqD29S9eXA_8',
    appId: '1:870201544031:web:aa92d138f2b5518b34faea',
    messagingSenderId: '870201544031',
    projectId: 'mango-2024',
    authDomain: 'mango-2024.firebaseapp.com',
    storageBucket: 'mango-2024.appspot.com',
    measurementId: 'G-KLL3MZCSZ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiGEOnsGq2DMXijZ0vD_hNV03NLt3xc00',
    appId: '1:870201544031:android:6cc5f40f8942504e34faea',
    messagingSenderId: '870201544031',
    projectId: 'mango-2024',
    storageBucket: 'mango-2024.appspot.com',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxaBstP4l2RwwaQhZRDoZcA111IMi9mwI',
    appId: '1:870201544031:ios:f6b355d3b266bfcb34faea',
    messagingSenderId: '870201544031',
    projectId: 'mango-2024',
    storageBucket: 'mango-2024.appspot.com',
    iosBundleId: 'com.example.mango',
  );
}
